version: "3.1"

volumes:
  pg_shares:

services:

  db_shares:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shares_db
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - ./pg_shares:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    restart: always
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - db_shares
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db_shares/shares_db"




#  pgadmin-compose:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "test123!"
#    ports:
#      - "16543:80"
#    depends_on:
#      - postgres